from __future__ import annotations

from app.models import MarketSnapshot


def simulated_polymarket_markets() -> list[MarketSnapshot]:
    return [
        MarketSnapshot(
            venue="polymarket",
            market_id="poly-btc-100k-2026",
            question="Will Bitcoin hit $100,000 before July 1, 2026?",
            slug="will-bitcoin-hit-100000-before-july-1-2026",
            yes_bid=0.61,
            yes_ask=0.63,
            no_bid=0.36,
            no_ask=0.38,
            yes_ask_size=18,
            no_ask_size=22,
            liquidity=18_500,
            volume_24h=4_900,
            close_time="2026-07-01T00:00:00Z",
            url="https://polymarket.com/event/will-bitcoin-hit-100000-before-july-1-2026",
            metadata={"category": "crypto"},
        ),
        MarketSnapshot(
            venue="polymarket",
            market_id="poly-fed-cut-june-2026",
            question="Will the Fed cut interest rates by June 2026?",
            slug="will-the-fed-cut-interest-rates-by-june-2026",
            yes_bid=0.47,
            yes_ask=0.49,
            no_bid=0.50,
            no_ask=0.52,
            yes_ask_size=25,
            no_ask_size=25,
            liquidity=31_000,
            volume_24h=8_300,
            close_time="2026-06-30T00:00:00Z",
            url="https://polymarket.com/event/will-the-fed-cut-interest-rates-by-june-2026",
            metadata={"category": "economy"},
        ),
        MarketSnapshot(
            venue="polymarket",
            market_id="poly-rain-nyc-2026-06-01",
            question="Will it rain in New York City on June 1, 2026?",
            slug="will-it-rain-in-new-york-city-on-june-1-2026",
            yes_bid=0.29,
            yes_ask=0.31,
            no_bid=0.68,
            no_ask=0.70,
            yes_ask_size=12,
            no_ask_size=17,
            liquidity=9_600,
            volume_24h=1_400,
            close_time="2026-06-01T23:59:00Z",
            url="https://polymarket.com/event/will-it-rain-in-new-york-city-on-june-1-2026",
            metadata={"category": "weather"},
        ),
    ]


def simulated_kalshi_markets() -> list[MarketSnapshot]:
    return [
        MarketSnapshot(
            venue="kalshi",
            market_id="KXBTC-26JUL01-T100000",
            ticker="KXBTC-26JUL01-T100000",
            question="Will Bitcoin reach $100,000 before Jul 1, 2026?",
            yes_bid=0.58,
            yes_ask=0.60,
            no_bid=0.37,
            no_ask=0.39,
            yes_ask_size=30,
            no_ask_size=30,
            liquidity=22_000,
            volume_24h=6_200,
            close_time="2026-07-01T00:00:00Z",
            url="https://kalshi.com/markets/KXBTC-26JUL01-T100000",
            metadata={"category": "crypto"},
        ),
        MarketSnapshot(
            venue="kalshi",
            market_id="KXFEDCUT-26JUN",
            ticker="KXFEDCUT-26JUN",
            question="Will the Fed cut rates by June 2026?",
            yes_bid=0.52,
            yes_ask=0.54,
            no_bid=0.45,
            no_ask=0.47,
            yes_ask_size=20,
            no_ask_size=19,
            liquidity=28_000,
            volume_24h=7_750,
            close_time="2026-06-30T00:00:00Z",
            url="https://kalshi.com/markets/KXFEDCUT-26JUN",
            metadata={"category": "economy"},
        ),
        MarketSnapshot(
            venue="kalshi",
            market_id="KXRAINNYC-26JUN01",
            ticker="KXRAINNYC-26JUN01",
            question="Rain in New York City on Jun 1, 2026?",
            yes_bid=0.32,
            yes_ask=0.34,
            no_bid=0.63,
            no_ask=0.65,
            yes_ask_size=14,
            no_ask_size=16,
            liquidity=11_000,
            volume_24h=1_900,
            close_time="2026-06-01T23:59:00Z",
            url="https://kalshi.com/markets/KXRAINNYC-26JUN01",
            metadata={"category": "weather"},
        ),
    ]
